version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    environment:
      CC_TEST_REPORTER_ID: f3bc884258d1cbcb4fee1ce87cb7310a278b971c55a6ef153007a653c597e051
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - store_artifacts: 
              path: test-results.xml
              prefix: tests
            - store_artifacts:
              path: coverage
              prefix: coverage
            - store_test_results:
              path: test-results.xml
workflows:
    build-and-test:
      jobs:
        - build-and-test